#!/bin/bash
FOLDER=$1

#setversion
cd $FOLDER && git describe --tags > app/View/Elements/version.ctp

rm $FOLDER/.git -rf
rm $FOLDER/.git* -rf
rm $FOLDER/*.sh -rf
rm $FOLDER/deploy -rf
rm $FOLDER/sql -rf
rm $FOLDER/puppet -rf
rm $FOLDER/Vagrantfile -rf